// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [//FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEQJufVh-UVdzKU60-z-n3IakpMwaYKzQ',
    appId: '1:933364418292:web:7f49de5c8a75a7ddaf80a1',
    messagingSenderId: '933364418292',
    projectId: 'jesus-worship-d3648',
    authDomain: 'jesus-worship-d3648.firebaseapp.com',
    storageBucket: 'jesus-worship-d3648.firebasestorage.app',
    measurementId: 'G-SJQWRCB5VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0YA4JsDjqwhP8GbAtMUCFjtqvlo4WZLA',
    appId: '1:933364418292:android:d4325530eefef92eaf80a1',
    messagingSenderId: '933364418292',
    projectId: 'jesus-worship-d3648',
    storageBucket: 'jesus-worship-d3648.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzDmubIpfRBsgy0PPal_K0WzwZj2FGvJU',
    appId: '1:933364418292:ios:0592fffcfd42832baf80a1',
    messagingSenderId: '933364418292',
    projectId: 'jesus-worship-d3648',
    storageBucket: 'jesus-worship-d3648.firebasestorage.app',
    iosBundleId: 'com.example.jesusWorshipCalendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzDmubIpfRBsgy0PPal_K0WzwZj2FGvJU',
    appId: '1:933364418292:ios:0592fffcfd42832baf80a1',
    messagingSenderId: '933364418292',
    projectId: 'jesus-worship-d3648',
    storageBucket: 'jesus-worship-d3648.firebasestorage.app',
    iosBundleId: 'com.example.jesusWorshipCalendarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEQJufVh-UVdzKU60-z-n3IakpMwaYKzQ',
    appId: '1:933364418292:web:c162d4397dd8ced2af80a1',
    messagingSenderId: '933364418292',
    projectId: 'jesus-worship-d3648',
    authDomain: 'jesus-worship-d3648.firebaseapp.com',
    storageBucket: 'jesus-worship-d3648.firebasestorage.app',
    measurementId: 'G-NF85MNEDD5',
  );

}